const FETCH_DATA = 'FETCH_DATA';
const ADD_DATA = 'ADD_DATA';
const REMOVE_DATA = 'REMOVE_DATA';
const DELETE_DATA = 'DELETE_DATA';
const POST_DATA = 'POST_DATA';

export {FETCH_DATA, ADD_DATA, REMOVE_DATA, DELETE_DATA, POST_DATA}