# Generated by Django 2.0.5 on 2018-10-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181021_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='active_order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
