# Generated by Django 2.0.5 on 2018-11-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_table_active_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp']},
        ),
    ]
